"""empty message

Revision ID: 1749c2500182
Revises: 32cbf9762357
Create Date: 2025-07-19 19:41:25.094171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1749c2500182'
down_revision = '32cbf9762357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.drop_constraint('aereal_images_farm_name_key', type_='unique')
        batch_op.drop_column('farm_name')

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.drop_constraint('ndvi_images_farm_name_key', type_='unique')
        batch_op.drop_column('farm_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('ndvi_images_farm_name_key', ['farm_name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('aereal_images_farm_name_key', ['farm_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
