"""empty message

Revision ID: 32cbf9762357
Revises: af4df9eea8f2
Create Date: 2025-07-19 02:00:25.285283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cbf9762357'
down_revision = 'af4df9eea8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['farm_name'])

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['farm_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('farm_name')

    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('farm_name')

    # ### end Alembic commands ###
