"""empty message

Revision ID: af4df9eea8f2
Revises: cdaf0b809613
Create Date: 2025-07-19 01:39:11.246779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4df9eea8f2'
down_revision = 'cdaf0b809613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('aereal_images_farm_location_key', type_='unique')
        batch_op.drop_constraint('aereal_images_farm_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'farm', ['farm_id'], ['id'])
        batch_op.drop_column('farm_name')
        batch_op.drop_column('farm_location')

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('farm_name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['farm_name'])
        batch_op.create_unique_constraint(None, ['farm_location'])
        batch_op.drop_constraint('farm_aereal_images_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('farm_ndvi_images_id_fkey', type_='foreignkey')
        batch_op.drop_column('aereal_images_id')
        batch_op.drop_column('ndvi_images_id')

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ndvi_images_farm_location_key', type_='unique')
        batch_op.drop_constraint('ndvi_images_farm_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'farm', ['farm_id'], ['id'])
        batch_op.drop_column('farm_name')
        batch_op.drop_column('farm_location')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_farm_location_key', type_='unique')
        batch_op.drop_constraint('user_farm_name_key', type_='unique')
        batch_op.drop_column('farm_name')
        batch_op.drop_column('farm_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_farm_name_key', ['farm_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('user_farm_location_key', ['farm_location'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('ndvi_images_farm_name_key', ['farm_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('ndvi_images_farm_location_key', ['farm_location'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('farm_id')

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ndvi_images_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aereal_images_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('farm_ndvi_images_id_fkey', 'ndvi_images', ['ndvi_images_id'], ['id'])
        batch_op.create_foreign_key('farm_aereal_images_id_fkey', 'aereal_images', ['aereal_images_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('farm_name')
        batch_op.drop_column('farm_location')

    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('farm_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('aereal_images_farm_name_key', ['farm_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('aereal_images_farm_location_key', ['farm_location'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('farm_id')

    # ### end Alembic commands ###
