"""empty message

Revision ID: cdaf0b809613
Revises: 66cc0b3f843f
Create Date: 2025-07-17 02:41:55.111677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdaf0b809613'
down_revision = '66cc0b3f843f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.drop_constraint('aereal_images_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aereal_images_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('farm_aereal_images_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aereal_images', ['aereal_images_id'], ['id'])
        batch_op.drop_column('aereal_images')

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.drop_constraint('ndvi_images_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ndvi_images_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aereal_images', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('farm_aereal_images_fkey', 'aereal_images', ['aereal_images'], ['id'])
        batch_op.drop_column('aereal_images_id')

    with op.batch_alter_table('aereal_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('aereal_images_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
